### ISSUE TITLE
How to access and change pixels in every frames?

### ISSUE THREAD

**Issue by zetsin** [devongovett/gif-stream#10]
I want to do something like this:
```js
fs
.createReadStream('in.gif')
.pipe(new GIFDecoder)
.pipe(concat(function(frames) {
  // change pixels for every frames
}))
.pipe(new GIFEncoder)
.pipe(fs.createWriteStream('out.gif'))
```

**Comment by devongovett** [comment]
You can make a transform stream to do that. See https://github.com/devongovett/color-transform  and https://github.com/devongovett/resizer-stream for examples.

If you can, you should try not to buffer an entire frame before processing. Sometimes that is not possible though, in the case of resizer-stream.

**Comment by zetsin** [comment]
Is there a bug about GIFDecoder?
```js
fs
.createReadStream('in.gif')
.pipe(new GIFDecoder)
.pipe(new GIFEncoder)
.pipe(fs.createWriteStream('out.gif'))
```

in.gif:
![in.gif](https://github.com/zetsin/public/raw/master/in.gif)
out.gif
![out.gif](https://github.com/zetsin/public/raw/master/out.gif)
