### ISSUE TITLE
Palette information in frame

### ISSUE THREAD

**Issue by sfrdmn** [devongovett/gif-stream#2]
Was looking into how I might grab color table / palette information out of the GIFDecoder stream. Looks like GIFEncoder looks for palette information in the input PixelStream via `frame.palette || this.format.palette`. GIFDecoder, however, doesn't annotate its pixel stream with this data. If it did, I could simply do `gifDecodeStream.pipe(gifEncodeStream).pipe(fileWriteStream)` and it would work (not that that's useful, but it means the quantization stream step becomes unnecessary)

Is there a particular reason for this? Could always just subclass GIFDecoder to include the data, but maybe it would be useful to add this to GIFDecoder?

BTW, what I'm trying to do is decode a single GIF into its individual frames, then reencode each frame as a static GIF.

Can submit a pull.

**Comment by sfrdmn** [comment]
Hmm well guess I was wrong on that `decode.pipe(encode)` example, since the decoder spits out RGB colorspace data. Still, any ideas on how to do a sort of identity transform from GIF to GIF without reindexing colors would be much appreciated!

**Comment by devongovett** [comment]
Let's add an option to get indexed data instead of rgb. I added [a similar option](https://github.com/devongovett/png-stream/blob/master/decoder.js#L32) to png-stream. [_outputScanline](https://github.com/devongovett/gif-stream/blob/master/decoder.js#L285) would just output the data as is instead of converting it to rgb in this case. Additionally, the `colorSpace` of the output format would need to be `'indexed'`, and the palette would need to be added to each frame object (GIFs can have different palettes per frame).

If you're feeling up to it, please write a PR. Thanks!

**Comment by sfrdmn** [comment]
Speaking of the palettes per frame: are these implemented correctly in GIFDecoder? My understanding is that, for any given frame, **if** there is a local color table, this should be used to decode the RGB data, **otherwise** a global color table should be used. Seems in the current implementation, the last decoded color table is always used, since it is clobbered as a property of the stream: https://github.com/devongovett/gif-stream/blob/4687e8f368ffa0acee9e2d227e3d493be5683c56/decoder.js#L137

Seems like you can have a GIF with a random local color table in some middle range frame which will then cause the remaining frames to be decoded with the local color table, rather than default back to the global one. Maybe this is just BS, as I haven't actually confirmed the bug. Can't even make that kind of GIF with Photoshop it seems.

**Comment by devongovett** [comment]
Not sure about that. I haven't seen any GIFs where per-frame palettes are used and one isn't provided for every frame. Not sure what the behavior is supposed to be in that case.

**Comment by sfrdmn** [comment]
From [the spec](http://www.w3.org/Graphics/GIF/spec-gif89a.txt):

    Active Color Table - Color table used to render the next graphic. If the next
    graphic is an image which has a Local Color Table associated with it, the
    active color table becomes the Local Color Table associated with that image.
    If the next graphic is an image without a Local Color Table, or a Plain Text
    Extension, the active color table is the Global Color Table associated with the
    Data Stream, if there is one; if there is no Global Color Table in the Data
    Stream, the active color table is a color table saved from a previous Data
    Stream, or one supplied by the decoder.

**Comment by devongovett** [comment]
Ok so sounds like you're right. Made a new issue for this: #5.
