### ISSUE TITLE
Convert frames to PNG or JPG Buffers

### ISSUE THREAD

**Issue by SimonBriche** [devongovett/gif-stream#6]
Hi,

This is not an issue but rather a question : what can you do with the frame objects that you obtain after calling the `concat` function, especially with the `pixels` and `palette` properties ? 
My ultimate goal is to add some graphics to an existing GIF (text and/or image on top of it). So I thought I could convert each frame to a Buffer that I can provide as the src of a Canvas.Image (using the node canvas module), and then generate my updated GIF.
Can I do that with your module (generate a Buffer that Canvas.Image could understand) ?

Thanks a lot.

**Comment by devongovett** [comment]
You could re-encode the frames and use `drawImage`, as you say: see [here](https://github.com/Automattic/node-canvas#imagesrcbuffer) for docs.

It would probably be faster to avoid the re-encode and use [createImageData](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/createImageData) to copy the decoded bitmap frame to the canvas directly.

**Comment by SimonBriche** [comment]
Thanks for your fast reply and your hints !

I've managed to get the pixels and put it in the canvas via `createImageData`, but the displayed pixels aren't correct. They are shrinked and in greyscale. I think that I have to "quantize" them, using the `pixels` and `palette` properties to retrieve the correct pixels in RGBA, but I can't figure the way to do it.

Below is my script so far, that grab a gif and send it back to the browser inside an express route : 

````
 var GIFDecoder = require('gif-stream/decoder');
 var concat = require('concat-frames');
 var neuquant = require('neuquant');

  // decode a GIF file to RGB pixels 
  fs.createReadStream(__dirname + '/path/to/gif.gif')
  .pipe(new GIFDecoder)
  .pipe(concat(function(frames) {
    // frames is an array of frame objects 
    // each one has a `pixels` property containing 
    // the raw RGB pixel data for that frame, as 
    // well as the width, height, etc. 

    var pixelBuffer = frames[0].pixels; // => greyscaled, left quart of the image only x4
    //var pixelBuffer = neuquant.index(frames[0].pixels, frames[0].palette); // => greyscaled, total image x4

    var canvas = new Canvas(frames[0].width,frames[0].height),
          ctx = canvas.getContext('2d');
    
    // convert buffer to Uint8ClampedArray
    var imgPixels = new Uint8ClampedArray(pixelBuffer);

    // create an ImageData object with correct dimensions
    var imgData = ctx.createImageData(frames[0].width, frames[0].height);
    // copy the pixels in the ImageData object
    for (var i=0;i<imgData.data.length;i+=4)
    {
      imgData.data[i+0]=imgPixels[i+0];
      imgData.data[i+1]=imgPixels[i+1];
      imgData.data[i+2]=imgPixels[i+2];
      imgData.data[i+3]=imgPixels[i+3];
    }
    ctx.putImageData(imgData,0,0);
    var buffer = canvas.toBuffer();

    res.writeHead(200, {'Content-Type': 'image/gif'});
    res.end(buffer); // Send the file data to the browser.
  }));

````

For information, I've successfully managed to grab a PNG, extract the pixels and send it back to the browser using your `png-stream/decoder`, so I think using the `createImageData` method was indeed relevant ^^ : 

````
  var PNGDecoder = require('png-stream/decoder');
  var concat = require('concat-frames');

  // decode a PNG file to RGB pixels 
  fs.createReadStream(__dirname + '/path/to/png.png')
  .pipe(new PNGDecoder)
  .pipe(concat(function(frames) {
    // frames is an array of frame objects 
    // each one has a `pixels` property containing 
    // the raw RGB pixel data for that frame, as 
    // well as the width, height, etc. 
    
    var pixelBuffer = frames[0].pixels;

    var canvas = new Canvas(frames[0].width,frames[0].height),
        ctx = canvas.getContext('2d');
    
    // convert buffer to Uint8ClampedArray
    var imgPixels = new Uint8ClampedArray(pixelBuffer);
    
    // create an ImageData object with correct dimensions
    var imgData = ctx.createImageData(frames[0].width, frames[0].height);
    // copy the pixels in the ImageData object
    for (var i=0;i<imgData.data.length;i+=4)
    {
      imgData.data[i+0]=imgPixels[i+0];
      imgData.data[i+1]=imgPixels[i+1];
      imgData.data[i+2]=imgPixels[i+2];
      imgData.data[i+3]=imgPixels[i+3];
    }
    ctx.putImageData(imgData,0,0);
    var buffer = canvas.toBuffer();

    res.writeHead(200, {'Content-Type': 'image/png'});
    res.end(buffer); // Send the file data to the browser.
  }));

````

Thanks !
(Sorry for the response delay, I live in France)

**Comment by devongovett** [comment]
You need to make sure the pixel data you're putting in the `createImageData` object is RGBA, not just RGB or another color space. If you try to copy an RGB buffer into an RGBA one, make sure that all of the alpha pixels are set to `1` and you skip the right number of pixels from the input buffer.

You can use the [color-transform](https://github.com/devongovett/color-transform) module to do the transformations for you.

Something like this maybe:

```javascript
fs.createWriteStream('/path/to/image.gif')
  .pipe(new GIFDecoder)
  .pipe(colorTransfom('rgba'))
  .pipe(concat(function(frames) {
    // do your processing. frames[i].pixels will be an RGBA buffer.
  });
```

**Comment by SimonBriche** [comment]
Hi,

It works ! Thanks a lot for your guidance !
I just had a few problems with some GIFs that seems corrupted. I had to import them in Photoshop, and tweak theirs export settings (in most cases, remove transparency support, or adapt the palette's number of colors) to have the correct display. Perhaps the GIFDecoder don't auto-adapt the pixels in regard of the real state of the GIF (transparent or not) ?

For the sake of posterity, here is the final code, assuming you're in a express route. It : 
- grabs a local GIF
- extract its frames
- create a canvas context for custom :
- create a GIFEncoder instance (from @eugeneware 's "gifencoder" module)
- for each frame, set GIF as background and add stuff via canvas as overlay
- compute the final modified GIF and send it to the browser

````
// decode a GIF file to RGB pixels 
fs.createReadStream('/path/to/image.gif')
.pipe(new GIFDecoder)
.pipe(new ColorTransform('rgba')) //encode the pixels in RGA space
.pipe(concat(function(frames) {
  // frames is an array of frame objects 
  // each one has a `pixels` property containing 
  // the raw RGB pixel data for that frame, as 
  // well as the width, height, etc. 
  console.log('GIF size : '+frames[0].width+'x'+frames[0].height+' with '+frames.length+' frames');

  //get the global image infos
  var imageWidth = frames[0].width, imageHeight = frames[0].height;
  //configure canvas
  var canvas = new Canvas(imageWidth,imageHeight), //size of the image
      ctx = canvas.getContext('2d');
  //configure GIF encoder
  var encoder = new GIFEncoder(imageWidth, imageHeight);
  encoder.start();
  encoder.setRepeat(0);   // 0 for repeat, -1 for no-repeat
  encoder.setQuality(10); // image quality. 10 is default.

  var i, j, framesLength = frames.length, pixelLength;
  var imgPixels, imgData, imgDataPixels;

  for(i=0;i<framesLength;i++){
    encoder.setDelay(frames[i].delay);  // frame delay in ms

    imgData = ctx.createImageData(imageWidth, imageHeight);
    imgPixels = frames[i].pixels;
    imgDataPixels = imgData.data;

    pixelLength = imgDataPixels.length;

    //fill the ImageData object
    for (j=0;j<pixelLength;j+=4)
    {
      imgDataPixels[j+0]=imgPixels[j+0];
      imgDataPixels[j+1]=imgPixels[j+1];
      imgDataPixels[j+2]=imgPixels[j+2];
      imgDataPixels[j+3]=imgPixels[j+3];
    }

    ctx.putImageData(imgData,0,0);

    // CUSTOM HERE YOUR CANVAS (add images, text, shapes, etc...)

    encoder.addFrame(ctx);
  }
  encoder.finish();

  var finalBuffer = encoder.out.getData();

  res.writeHead(200, {'Content-Type': 'image/gif'});
  res.end(finalBuffer); // Send the file data to the browser.
}));
````

Performance wise, it's the GIFEncoder.addFrame that take the most of the process time. 
For a 300x226 GIF with 48 frames : 
- with GIFEncoder.addFrame : fill ImageData -> 2519ms, total encode -> 2814ms 
- without GIFEncoder.addFrame : fill ImageData -> 46ms, total encode -> 319ms 

Thanks again for your time.

**Comment by devongovett** [comment]
Glad it works. You probably could have used the gif encoder from this module as well if you wanted. You'd need to also use the neuquant module to quantize the pixel data as well. See the encoding example here: https://github.com/devongovett/gif-stream#encoding-example.
